version: '3.6'

services:
  # central
  server_0101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 16200:16200
    command: /data/loris/bin/server -N0101 -I${listen_ip}:16200 -L7 -V/data/server/${version_name}

  #gateway
  server_0201:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 16203:16203
      - 16204:16204
    depends_on: 
      - server_0101
    command: /data/loris/bin/server -N0201 -I${listen_ip}:16203,${listen_ip}:16204 -L7 -V/data/server/${version_name} -c${central}:16200
  
  #core
  server_0301:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server -N0301 -L7 -A -F -M10000 -V/data/server/${version_name} -c${central}:16200
  
  #extra
  server_0401:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server -N0401 -L7 -V/data/server/${version_name} -c${central}:16200
  
  #status
  server_C101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server -NC101 -I${listen_ip}:16202 -L7 -V/data/server/${version_name} -c${central}:16200
  
  #cross
  server_8701:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server  -N8701 -L7 -V/data/server/${version_name} -c${central}:16200
  
  #cross
  server_CA01:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server  -NCA01 -I${listen_ip}:16207 -L7 -V/data/server/${version_name} -c${central}:16200
  
  #web
  web:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 16201:16201
    depends_on: 
      - server_0101
    command: /data/loris/bin/web -V/data/server/${version_name} -I:16201 -c${central}:16200