version: '3.6'

services:
  # central
  server_0101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 17000:17000
    command: /data/loris/bin/server -N0101 -I${listen_ip}:17000 -L7 -V/data/server/${version_name}

  #gateway
  server_0201:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 17003:17003
      - 17004:17004
    depends_on: 
      - server_0101
    command: /data/loris/bin/server -N0201 -I${listen_ip}:17003,${listen_ip}:17004 -L7 -V/data/server/${version_name} -c${central}:17000
  
  #router
  server_C801:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 17006:17006
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server -NC801 -I${listen_ip}:17006 -L7 -V/data/server/${version_name} -c${central}:17000

  #core
  server_0301:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server -N0301 -L7 -A -F -M10000 -V/data/server/${version_name} -c${central}:17000
  
  #extra
  server_0401:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server -N0401 -L7 -V/data/server/${version_name} -c${central}:17000
  
  # #status
  # server_C101:
  #   image: $image_name
  #   volumes: 
  #     -   $project:/data/loris
  #     -   $runtime_dir:/data/server/${version_name}
  #   depends_on: 
  #     - server_0101
  #     - server_0201
  #   command: /data/loris/bin/server -NC101 -I${listen_ip}:17002 -L7 -V/data/server/${version_name} -c${central}:17000
  
  #cross
  server_8701:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server  -N8701 -L7 -V/data/server/${version_name} -c${central}:17000
  
  #global
  server_CA01:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 17007:17007
    depends_on: 
      - server_0101
      - server_0201
    command: /data/loris/bin/server  -NCA01 -I${listen_ip}:17007 -L7 -V/data/server/${version_name} -c${central}:17000
  
  #web
  web:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/server/${version_name}
    ports:
      - 17001:17001
    depends_on: 
      - server_0101
    command: /data/loris/bin/web -V/data/server/${version_name} -I:17001 -c${central}:17000