version: '3.6'

services:
  # central
  global_0101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    ports:
      - 16310:16310
    command: /data/loris/bin/global -N0101 -L7  -V/data/global -I${listen_ip}:16310

  #gateway
  global_C101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    ports:
      - 16313:16313
      - 16314:16314
    depends_on: 
      - global_0101
    command: /data/loris/bin/global -NC101 -L7  -V/data/global -I${listen_ip}:16313,${listen_ip}:16314 -c${central}:16310
  
  #ladder
  global_C201:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    depends_on: 
      - global_0101
      - global_C101
    command:  /data/loris/bin/global -NC201 -L7 -V/data/global -c${central}:16310
  
  #base
  global_C301:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    depends_on: 
      - global_0101
      - global_C101
    command: /data/loris/bin/global -NC301 -L7 -V/data/global -c${central}:16310
  
  
  #web
  global_web:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    ports:
      - 16312:16312
    depends_on: 
      - global_0101
    command: /data/loris/bin/globalWeb -V/data/global -I:16312