version: '3.6'

services:
  # central
  global_0101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    ports:
      - 16810:16810
    command: /data/loris/bin/global -N0101 -L7  -V/data/global -I${listen_ip}:16810

  #gateway
  global_C101:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    ports:
      - 16813:16813
      - 16814:16814
    depends_on: 
      - global_0101
    command: /data/loris/bin/global -NC101 -L7  -V/data/global -I${listen_ip}:16813,${listen_ip}:16814 -c${central}:16810
  
  #ladder
  global_C201:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    depends_on: 
      - global_0101
      - global_C101
    command:  /data/loris/bin/global -NC201 -L7 -V/data/global -c${central}:16810
  
  #base
  global_C301:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    depends_on: 
      - global_0101
      - global_C101
    command: /data/loris/bin/global -NC301 -L7 -V/data/global -c${central}:16810
  
  
  #web
  global_web:
    image: $image_name
    volumes: 
      -   $project:/data/loris
      -   $runtime_dir:/data/global
    ports:
      - 16812:16812
    depends_on: 
      - global_0101
    command: /data/loris/bin/globalWeb -V/data/global -I:16812